repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff
        args: [ --fix ]
        stages: [pre-commit]
      
      - id: ruff-format
        stages: [pre-commit]

      - id: ruff
        args: [ --no-fix ]
        stages: [pre-push]
        
      - id: ruff-format
        args: [ --check ]
        stages: [pre-push]
